language: node_js
node_js:
- 8.4.0
services:
- postgresql
before_script:
- mv config/config.example.js config/config.js
- npm run sequelize -- --env test db:create
- npm run sequelize -- --env test db:migrate
deploy:
  app:
    master: api-questions
  provider: heroku
  api_key:
    secure: YaXq68PjW835LJbdguaDqQ2hhnfChLQbGGcdOsIzuqWV//4XX2ewyGEVzZ5dPa1zlJfUQi0vp7Ek4KI+sLn8KF/H2lIwzVRPYVLGKd8aGHML7NBFp9bPA5PlEN1nUQaaCRcGofuO3PZ59uzdWj1v/8jHZsilhq7wwKlNygjjtIlas7Y8jHPzbbZyqadOmLJueS2+WjQVXJ12zs9m1/bbk3DP04wD1uv7rqBXSQddtbVHUzcZomtohcjpDaexolw5PXvUmYUo0do/vH2OWHXQBndQHrMxzmpCrXCcA9jtvIJ6tlU0IDPQvpc5zhg4yM2cTx7p6x0i1zgzG5Nk/OFGLOWHEfPxfNZ3YeOdboSc+asX2eDsufhicFXk9vCKH9fEamEYjpgUMg56wFr2nUbUuUZE6vjuat9KnkoszXF3NfdhNGbGIjICbSSpIHUaBJVh+ktDrGvNshfYpmknp7V8fbsLS6wat2yUSqJhpmeWbzkESkt/t2Og19VtfwrKUjR3XYBVCT8z4DTI8j25D5NiH67cJaC2aqu0F2ZyhgqGp7E3i86G4tS+z2wNqrELDl+/ZXb6KsTzIIqUJ5W5CF9SBGPrTebNfgn5UM5GZ3mIM93W8bSid13rahD0o68zMoV9O221vpaPsCaSSI6ajL83aMfr1hDz9jH5jn+rxmsk8S8=
