language: node_js
node_js:
- 8.4.0
services:
- postgresql
before_script:
- mv config/config.example.js config/config.js
- npm run sequelize -- --env test db:create
- npm run sequelize -- --env test db:migrate
deploy:
  app:
    master: api-questions
  provider: heroku
  api_key:
    secure: H1I1shSL7Ciu3vDItAFk2oZ/MLAe6Fb+ZL6/XP/G9CNvLsgXlmzdKfXb56VA89YK7XhGQjJLvzOz0N/L4Gcl0Tpdmjq/qW/L0yw3Ry+W103M8tFgCc9Mo3VTq1EA5IIzV/u4lxFyRn/Mp3lwc0yWTEQ330l0erTBV2bBP/YniGzB2QxP7H07gh3XV5iFLUlyueKkru3NPiBQfdTch4FBCfrKdF/yiijO99klCqNH4eJ1LgzMjmpXJ+zTJAc8e6R3UkWLiSn9ZrFa4m0WYLyDVICuKvSDs8aKOh4WAcZGktZJSmVobPa1Asg3UCcTVYgiW7fgh++HkEc3o2FtRgoSqlk/Ib6MQXnM1o4JF15j8Re7XKHHdFJD5vhDDTtj16gKyaHDEvFmCsl2rXoDm1M2o3gUhmizjtfl7qMUFW9Y0dfSMLJj2hWV3bcWkhUk70SlEosSTBGb0qIuJUuf/xK02E1VJrUO8N0L59Gx/oVTsOUAF/5gXp8j90Q4obJ7PNt3z9rAdhp4JZxajo8iO8g9dBDRgwcW4bPVg95qL9iPjsuV2tzJeFwOv8qnsVGLxDgivtHf52fvLKFn4v3b6R4dF0mkDWCS6fBxgi0ClRe6KcOxqGUGz0nWDmq7FqDP/b9NDyOM2ri00OR1esinXuz0BBwWBdlXw+rGOkYDZODWd9c=
